### ISSUE TITLE
tests running too early (before compilation check)

### ISSUE THREAD

**Issue by DanielRuf** [php/php-windows-builder#5] opened 2024-09-08 11:29 UTC
Do I miss some step or are tests running before the compilation and failing due to missing dll file (which makes sense because the compilation starts afterwards)?

https://github.com/DanielRuf/php-spx/actions/runs/10759348451/job/29835929440

Compare that to https://github.com/DanielRuf/php-spx/actions/runs/10759501360/job/29836256905

**Comment by cmb69** [comment] 2024-09-08 12:18
The problem is that you are not actually building any extensions:

https://github.com/DanielRuf/php-spx/blob/windows-build/.github/workflows/main.yml#L19

results in

https://github.com/DanielRuf/php-spx/actions/runs/10759348451/job/29835929440#step:2:129

A few lines below you can see that `--enable-xdebug` is invalid. That should be `--enable-spx` instead.

Anyhow, I suggest to start by adding a config.w32 as Windows pendant of config.m4. This are similar, but are written in JScript. For a start, maybe something like the following might work:
````javascript
ARG_ENABLE("spx", "whether to enable SPX extension", "no");

if (PHP_SPX != "no") {
    AC_DEFINE(HAVE_SPX, 1, "Define to 1 if the PHP extension 'spx' is available.");
    EXTENSION("spx",
        "src/php_spx.c" +
        "src/spx_profiler.c" +
        "src/spx_profiler_tracer.c" +
        "src/spx_profiler_sampler.c" +
        "src/spx_reporter_full.c" +
        "src/spx_reporter_fp.c" +
        "src/spx_reporter_trace.c" +
        "src/spx_metric.c" +
        "src/spx_resource_stats.c" +
        "src/spx_hmap.c" +
        "src/spx_str_builder.c" +
        "src/spx_output_stream.c" +
        "src/spx_php.c" +
        "src/spx_stdio.c" +
        "src/spx_config.c" +
        "src/spx_utils.c" +
        "src/spx_fmt.c");
}
````

**Comment by cmb69** [comment] 2024-09-08 12:27
Oops, forgot the spaces to separate the extension files above.

**Comment by DanielRuf** [comment] 2024-09-08 13:11
Thanks, I fixed the args. I basically oversaw this part.

**Comment by DanielRuf** [comment] 2024-09-08 13:47
Besides that, I think the compilation check should be done before running the tests. As my original assumption still stands, I will reopen this issue.

**Comment by shivammathur** [comment] 2024-09-17 11:27
@DanielRuf Fixed in https://github.com/php/php-windows-builder/commit/6b8fa15827ce895511b4abdd3a5ac66e4c500b12

**Closed by shivammathur** 2024-09-17 11:27 UTC
